### ISSUE TITLE
Unseen Speaker Adaptation

### ISSUE THREAD

**Issue by Liujingxiu23** [KevinMIN95/StyleSpeech#1]
For "unseen Speaker Adaptation" , did you refine the model using the data of target speaker, or just using MelStyleEncoder to get ws which adjust the output (like zero-shot/one-shot)?

**Comment by KevinMIN95** [comment]
No, we did not refine the model. We just use  MelStyleEncoder **without finetuning** to get ws.

**Comment by Liujingxiu23** [comment]
@KevinMIN95  Get it, thank you for your reply!
