### ISSUE TITLE
synthesized audio is not similar with reference audio

### ISSUE THREAD

**Issue by tranquangchung** [KevinMIN95/StyleSpeech#11]
Dear author @KevinMIN95 

Thank you for sharing the interesting project. 
I use pretrained model (Stylespeech and Meta-Stylespeech) and Melgan (pretrained model).
I also use the same people in the page (https://stylespeech.github.io/) to evaluate **Trained Speaker** and **Unseen Speaker**. However, the synthesized audio is not good as you report.
Could you give me some advice to reproduce the similar result that you report. 
Best Regard

**Comment by KevinMIN95** [comment]
Is the synthesized audio not good in terms of quality or similarity?

**Comment by tranquangchung** [comment]
Both of them (quality and similarity)
Below is audio that I use pretrained model to synthesize (Meta-Stylespeech and MelGan)
Because Github does not allow users to upload mp3 files, so I will upload zip files instead.
Train Speaker ID  (1463, 6492)
Unseen Speaker (p237, p297)
[audio_demo.zip](https://github.com/KevinMIN95/StyleSpeech/files/7611102/audio_demo.zip)

My team really want to base on your research to develop my own research. I am waiting for your help.

**Comment by KevinMIN95** [comment]
Are you using the MelGAN trained by yourself?  I think it can be problem of the MelGAN...

**Comment by dtx525942103** [comment]
sampling_rate: 16000，it sames the melgan is not for 16000

**Comment by tranquangchung** [comment]
Currently, I am training MelGan with sample rate 16000 for 2 days. However, the synthesized audio quality is still poor, I will wait for ending epochs (3000).  
I'm very happy if you can share the pretrained model MelGan to me and my email: bktranquangchung@gmail.com
Best Regard
@KevinMIN95

**Comment by KevinMIN95** [comment]
If you are using the official code for MelGAN, you should use the same processing way to convert audio to mel. It is slightly different.
