### ISSUE TITLE
Error when running train.py (models/VarianceAdaptor.py line 52)

### ISSUE THREAD

**Issue by SeongYeonPark** [KevinMIN95/StyleSpeech#16]
When running train.py, 
models/VarianceAdaptor.py line 52:         x = self.ln(x) + pitch_embedding + energy_embedding

returns an error. 
The shape of x seems to be [Batch_size, max_text_input_length, 256].
The shape of the other two seems to be [Batch_size, ??????, 256]   (I don't know what pitch_embedding.shape(1) should be.)

Is there a solution to this?

**Comment by KevinMIN95** [comment]
Pitch embedding and energy_embedding should have the same length as x (phonemes). Please check preprocessed files whether they have the same lengths.
