### ISSUE TITLE
How to better convert mel-spectrogram generated to audio

### ISSUE THREAD

**Issue by purnima291** [KevinMIN95/StyleSpeech#4]
After running the inference command, the result is a png file showing spectrograms. So I tried to do some changes in the synthesize.py file to covert generated mel -spectrogram to audio file. I used librosa for this purpose. Below is the code snippet to do so.
![Screenshot from 2021-08-11 22-20-24](https://user-images.githubusercontent.com/39857286/129070300-414c323d-ec1f-4616-ba8e-2898f40a9c41.png)
But the audio obtained is blank. 
Can you please help me out to convert the mel to proper audio? I am not yet an expert in this field. @KevinMIN95 your help is appreciated here. 
Thank you

**Comment by KevinMIN95** [comment]
Hi, I'm afraid that I've never used a griffinlim vocoder... I just recommend you use other vocoder models such as MelGAN.

**Comment by purnima291** [comment]
Thanks for the suggestion. I will surely try it out.
